<?php
/**
 * Gutenberg block registration for SchoolDigger Widgets.
 *
 * Registers the "schooldigger/widget" block with a server-side render callback.
 * The block is a dynamic block (save returns null in JS) — all HTML is
 * generated by the PHP render callback at display time.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class SD_Widgets_Block {

    /**
     * Register the block type.
     */
    public static function register() {
        $block_dir = SD_WIDGETS_DIR . 'blocks/schooldigger-widget';

        // Only register if the build output exists.
        if ( ! file_exists( $block_dir . '/build/index.js' ) ) {
            return;
        }

        register_block_type( $block_dir, array(
            'render_callback' => array( __CLASS__, 'render_block' ),
        ) );

        // Pass plugin settings to the block editor via inline script data.
        add_action( 'enqueue_block_editor_assets', array( __CLASS__, 'enqueue_editor_data' ) );
    }

    /**
     * Pass settings and catalog to the editor as a global JS object.
     */
    public static function enqueue_editor_data() {
        $catalog  = sd_widgets_get_catalog();
        $states   = sd_widgets_get_states();
        $app_id   = get_option( 'sd_widgets_app_id', '' );
        $base_url = get_option( 'sd_widgets_base_url', 'https://widgets.schooldigger.com' );

        // Convert PHP catalog to a JSON-safe format for the editor.
        $editor_catalog = array();
        foreach ( $catalog as $widget_id => $widget ) {
            $editor_catalog[ $widget_id ] = array(
                'name'        => $widget['name'],
                'description' => $widget['description'],
                'category'    => $widget['category'],
                'minimumTier' => $widget['minimumTier'],
                'icon'        => $widget['icon'],
                'parameters'  => $widget['parameters'],
            );
        }

        wp_add_inline_script(
            'schooldigger-widget-editor-script',
            'window.sdWidgetsEditor = ' . wp_json_encode( array(
                'catalog' => $editor_catalog,
                'states'  => $states,
                'appId'       => $app_id,
                'baseUrl'     => $base_url,
                'settingsUrl' => admin_url( 'options-general.php?page=schooldigger-widgets' ),
            ) ) . ';',
            'before'
        );
    }

    /**
     * Server-side render callback for the block.
     *
     * @param array $attributes Block attributes.
     * @return string HTML output.
     */
    public static function render_block( $attributes ) {
        $widget_type = isset( $attributes['widgetType'] ) ? sanitize_text_field( $attributes['widgetType'] ) : '';
        if ( empty( $widget_type ) ) {
            return '<!-- SchoolDigger Widget: no widget type selected -->';
        }

        $app_id = get_option( 'sd_widgets_app_id', '' );
        if ( empty( $app_id ) ) {
            return '<!-- SchoolDigger Widget: no App ID configured -->';
        }

        $config = isset( $attributes['config'] ) ? sanitize_text_field( $attributes['config'] ) : '';
        if ( empty( $config ) ) {
            $config = get_option( 'sd_widgets_default_config', '' );
        }

        $params   = isset( $attributes['params'] ) ? $attributes['params'] : array();
        $reserved = array(); // Block params are already clean — no reserved keys to skip.

        return sd_widgets_render_container( $widget_type, $app_id, $config, $params, $reserved, 'block' );
    }
}
